language: node_js
node_js:
- '10'
script:
- npm install -g firebase-tools
- npm install
- npm test
deploy:
-
  provider: script
  script: firebase deploy --project utokyo-dev --token $FIREBASE_TOKEN
  on:
    branch: master
notifications:
  slack: ut-jichikai137:XZprizkUhgGINIW76EiYKLNo
