language: node_js
node_js:
- '10'
script:
- npm install -g firebase-tools
- npm install
after_success:
- firebase deploy --project utokyo-dev --token $FIREBASE_TOKEN
notifications:
  slack: ut-jichikai137:XZprizkUhgGINIW76EiYKLNo
