language: node_js
node_js:
- '10'
install:
- openssl aes-256-cbc -K $encrypted_884d48b7f311_key -iv $encrypted_884d48b7f311_iv -in utokyo-dev_service-account-key.json.enc -out functions/utokyo-dev_service-account-key.json -d
- npm --prefix ./functions install
- npm install -g firebase-tools
script:
- npm --prefix ./functions test
deploy:
-
  provider: script
  skip_cleanup: true
  script: firebase deploy --non-interactive --project=utokyo-dev --token=$FIREBASE_TOKEN
  on:
    branch: master
notifications:
  slack: ut-jichikai137:XZprizkUhgGINIW76EiYKLNo
