language: node_js
node_js:
- stable
- '10'
deploy:
  provider: firebase
  token:
  secure: "cVp+QeQNjTuFy4Fnm0pafb4KN5q4b2ZZdnnQFmSWNHjxj/s9aYTSY6Arzo1kxNcKlRROejjaORTVaSkEpCpiJC1lyACTmNlYmmXYNt/WOgQsOnGpzAzQirn5Gjz1qzP11um9qfuw91D/4gDj0Cgman5fLPcUPdY5BcVj9+0G1sG6GDZ2hdOpqrLHdnRTjsHKPw3isThDvxcU6RAJ0GzqIMcbChdF8/rXlxsCXCIGjk63gq3qGcbkO7u2LKb/HbZM16YjHTpI4k63/BtN/hf/OCMWi5hzhAWVIzObp4hul/TTJybdPn1xnM+HBK42xQ8p2O9AGrS+5a7XxbYPi3/+M9gYBKEeadxyToivFGqTZRW9L29RmlOwLhbMRmFcsVtdVkUTpMPjudEbbQ6R/uQxm1aPng4zslQq1HaNKIp9hEgeykOvtBsUd1cAUvJ6LNE72T3nKKWG6ycwJxGorfENUCOZzUiOn6o9aIxnnor/BDRCTE2LlUing37cXHJrBiAN9OJ1Y2x/Fsmw2sP64o2yHlUT5ARWb6EeXY6D1fUWe9aTRHoJLHMXxGLZrw5/FstlFAUcVgB2oIY+12fLD1Yt278Azyj8HRdCyjlxXnHXYTn2Ek/I2WcJxXrE+QX4psQUr3HE+X/jdQkwYyAdvEs56yUnk2sI2jzksIb4MF8E0Wk="
